
export type LogType = "service log" | "patient registered" | "doctor registered" | "Admin registered" | "Appointment slot created" | "Appointment request declined"
    | "Doctor logged in"
    | "Appointment request rescheduled"
    | "Appointment request cancelled"
    | "Appointment cancelled"
    | "Appointment request rejected"
    | "Record request sent"
    | "Allergy added"
    | "Lab request sent"
    | "Labs request sent"
    | "Diagnosis added"
    | "Diagnoses retrieved"
    | "Surgery added"
    | "Visit scheduled"
    | "Profile picture uploaded"
    | "Profile picture removed"
    | "Account deleted"
    | "Payment method added"
    | "Rate set"
    | "Doctor profile updated"
    | "Password reset"
    | "Patient profile updated"
    | "Appointment cancelled"
    | "Prescription generated"
    | "Patient registered"
    | "Patient logged in"
    | "Patient account deleted"
    | "Appointment request"
    | "Appointment request accepted"
    | "Appointment rescheduled"
    | "Records request accepted"
    | "Prescription viewed"
    | "Doctor removed from favourites"
    | "Doctor added to favourites"
    | "Vitals added"
    | "Lab picture uploaded"
    | "Review submitted" | "Consultation started" | "Consultation ended" | "Doctor registered"
    | "Referral";