export const DOCTORS_DATA = [
  {
    notifications: {
      email: true,
      status: false,
      records: true,
      messages: true,
      appointments: false,
    },
    languages: ["English Language", "Mandarin", "Hindi"],
    email: "raj.patel@medmail.com",
    isActive: true,
    firstName: "Raj",
    lastName: "Patel",
    MDCRegistration: "624813975310",
    dob: "1985-07-12",
    gender: "male",
    contact: "0441234567",
    address: "78 Oak Street",
    city: "Mumbai",
    qualifications: ["MBBS", "MS Orthopedics"],
    specializations: ["Orthopedic Surgery", "Sports Medicine"],
    experience: 15,
    verification_status: "verified",
    education: [
      {
        degree: "MBBS",
        school: "All India Institute of Medical Sciences",
      },
      {
        degree: "MS Orthopedics",
        school: "Johns Hopkins University",
      },
    ],
    bio: "Experienced orthopedic surgeon specializing in sports-related injuries and minimally invasive procedures. Passionate about helping athletes return to peak performance.",
    awards: [
      "Best Orthopedic Surgeon - Mumbai Medical Association",
      "Innovation in Surgical Techniques Award",
    ],
    rate: {
      amount: 180,
      lengthOfSession: 45,
    },
  },
  {
    notifications: {
      email: true,
      status: true,
      records: false,
      messages: true,
      appointments: true,
    },
    languages: ["English Language", "German", "Italian"],
    email: "emma.schmidt@docmail.de",
    isActive: true,
    firstName: "Emma",
    lastName: "Schmidt",
    MDCRegistration: "135792468013",
    dob: "1990-03-25",
    gender: "female",
    contact: "0157891011",
    address: "15 Blumenstraße",
    city: "Berlin",
    qualifications: ["MD", "Board Certified in Dermatology"],
    specializations: ["Dermatology", "Cosmetic Dermatology"],
    experience: 8,
    verification_status: "verified",
    education: [
      {
        degree: "Doctor of Medicine",
        school: "Charité - Universitätsmedizin Berlin",
      },
    ],
    bio: "Dedicated dermatologist with a focus on holistic skincare and innovative cosmetic procedures. Committed to helping patients feel confident in their skin.",
    awards: ["Rising Star in Dermatology - European Dermatology Forum"],
    rate: {
      amount: 150,
      lengthOfSession: 30,
    },
  },
  {
    notifications: {
      email: false,
      status: true,
      records: true,
      messages: false,
      appointments: true,
    },
    languages: ["English Language", "Arabic", "French"],
    email: "aisha.al-mansour@healthmail.sa",
    isActive: true,
    firstName: "Aisha",
    lastName: "Al-Mansour",
    MDCRegistration: "246813579024",
    dob: "1982-11-30",
    gender: "female",
    contact: "0501234567",
    address: "42 King Fahd Road",
    city: "Riyadh",
    qualifications: ["MD", "Fellowship in Oncology"],
    specializations: ["Medical Oncology", "Hematology"],
    experience: 18,
    verification_status: "verified",
    education: [
      {
        degree: "Doctor of Medicine",
        school: "King Saud University",
      },
      {
        degree: "Fellowship in Oncology",
        school: "MD Anderson Cancer Center",
      },
    ],
    bio: "Compassionate oncologist dedicated to providing cutting-edge cancer treatments. Advocate for patient-centered care and increased cancer awareness in the Middle East.",
    awards: [
      "Excellence in Oncology Research - Gulf Cooperation Council",
      "Physician of the Year - King Faisal Specialist Hospital",
    ],
    rate: {
      amount: 220,
      lengthOfSession: 60,
    },
  },
  {
    notifications: {
      email: true,
      status: false,
      records: true,
      messages: true,
      appointments: false,
    },
    languages: ["English Language", "Japanese", "Korean"],
    email: "hiroshi.tanaka@medmail.jp",
    isActive: true,
    firstName: "Hiroshi",
    lastName: "Tanaka",
    MDCRegistration: "369258147036",
    dob: "1975-09-18",
    gender: "male",
    contact: "0312345678",
    address: "7 Sakura Street",
    city: "Tokyo",
    qualifications: ["MD", "PhD in Cardiology"],
    specializations: ["Cardiology", "Interventional Cardiology"],
    experience: 25,
    verification_status: "verified",
    education: [
      {
        degree: "Doctor of Medicine",
        school: "University of Tokyo",
      },
      {
        degree: "PhD in Cardiology",
        school: "Osaka University",
      },
    ],
    bio: "Renowned cardiologist with extensive experience in complex cardiovascular interventions. Committed to advancing cardiac care through research and innovation.",
    awards: [
      "Lifetime Achievement Award - Japanese Circulation Society",
      "Distinguished Researcher - Asia Pacific Society of Cardiology",
    ],
    rate: {
      amount: 300,
      lengthOfSession: 45,
    },
  },
  {
    notifications: {
      email: true,
      status: true,
      records: false,
      messages: true,
      appointments: true,
    },
    languages: ["English Language", "Portuguese", "Spanish"],
    email: "carla.silva@saudemail.br",
    isActive: true,
    firstName: "Carla",
    lastName: "Silva",
    MDCRegistration: "147258369258",
    dob: "1988-06-15",
    gender: "female",
    contact: "0119876543",
    address: "23 Avenida Paulista",
    city: "São Paulo",
    qualifications: ["MD", "Residency in Pediatrics"],
    specializations: ["Pediatrics", "Neonatology"],
    experience: 10,
    verification_status: "verified",
    education: [
      {
        degree: "Doctor of Medicine",
        school: "Universidade de São Paulo",
      },
    ],
    bio: "Caring pediatrician with a special focus on neonatal care. Dedicated to improving child health outcomes in underserved communities.",
    awards: ["Young Pediatrician of the Year - Brazilian Pediatric Society"],
    rate: {
      amount: 120,
      lengthOfSession: 30,
    },
  },
  {
    notifications: {
      email: false,
      status: true,
      records: true,
      messages: false,
      appointments: true,
    },
    languages: ["English Language", "Russian", "Ukrainian"],
    email: "viktor.petrov@medmail.ru",
    isActive: true,
    firstName: "Viktor",
    lastName: "Petrov",
    MDCRegistration: "258369147369",
    dob: "1970-12-03",
    gender: "male",
    contact: "0495551234",
    address: "56 Nevsky Prospekt",
    city: "Saint Petersburg",
    qualifications: ["MD", "PhD in Neurosurgery"],
    specializations: ["Neurosurgery", "Spinal Surgery"],
    experience: 30,
    verification_status: "verified",
    education: [
      {
        degree: "Doctor of Medicine",
        school: "First Moscow State Medical University",
      },
      {
        degree: "PhD in Neurosurgery",
        school: "Saint Petersburg State Medical University",
      },
    ],
    bio: "Highly skilled neurosurgeon with three decades of experience in complex brain and spinal cord surgeries. Pioneer in minimally invasive neurosurgical techniques.",
    awards: [
      "State Prize in Science and Technology",
      "Honorary Surgeon of the Russian Federation",
    ],
    rate: {
      amount: 350,
      lengthOfSession: 60,
    },
  },
  {
    notifications: {
      email: true,
      status: false,
      records: true,
      messages: true,
      appointments: false,
    },
    languages: ["English Language", "Swahili", "French"],
    email: "amina.osei@healthmail.ke",
    isActive: true,
    firstName: "Amina",
    lastName: "Osei",
    MDCRegistration: "741852963147",
    dob: "1992-08-20",
    gender: "female",
    contact: "0712345678",
    address: "89 Uhuru Gardens",
    city: "Nairobi",
    qualifications: ["MBChB", "Master's in Public Health"],
    specializations: ["Family Medicine", "Public Health"],
    experience: 7,
    verification_status: "verified",
    education: [
      {
        degree: "Bachelor of Medicine and Bachelor of Surgery",
        school: "University of Nairobi",
      },
      {
        degree: "Master's in Public Health",
        school: "London School of Hygiene & Tropical Medicine",
      },
    ],
    bio: "Passionate family physician and public health advocate. Committed to improving healthcare access and outcomes in rural African communities.",
    awards: ["Young Leader in African Healthcare - African Union"],
    rate: {
      amount: 80,
      lengthOfSession: 45,
    },
  },
  {
    notifications: {
      email: true,
      status: true,
      records: false,
      messages: true,
      appointments: true,
    },
    languages: ["English Language", "Swedish", "Danish"],
    email: "erik.andersson@lakaremail.se",
    isActive: true,
    firstName: "Erik",
    lastName: "Andersson",
    MDCRegistration: "963852741258",
    dob: "1980-04-10",
    gender: "male",
    contact: "0763214569",
    address: "12 Kungsgatan",
    city: "Stockholm",
    qualifications: ["MD", "Specialist in Internal Medicine"],
    specializations: ["Internal Medicine", "Endocrinology"],
    experience: 17,
    verification_status: "verified",
    education: [
      {
        degree: "Doctor of Medicine",
        school: "Karolinska Institute",
      },
    ],
    bio: "Dedicated internist with a focus on endocrine disorders. Committed to patient education and holistic approach to metabolic health.",
    awards: ["Clinical Excellence Award - Swedish Medical Association"],
    rate: {
      amount: 190,
      lengthOfSession: 40,
    },
  },
  {
    notifications: {
      email: false,
      status: true,
      records: true,
      messages: false,
      appointments: true,
    },
    languages: ["English Language", "Greek", "Turkish"],
    email: "elena.papadopoulos@docmail.gr",
    isActive: true,
    firstName: "Elena",
    lastName: "Papadopoulos",
    MDCRegistration: "852963741369",
    dob: "1987-02-14",
    gender: "female",
    contact: "0306543210",
    address: "34 Ermou Street",
    city: "Athens",
    qualifications: ["MD", "Specialist in Obstetrics and Gynecology"],
    specializations: ["Obstetrics", "Gynecology", "Reproductive Endocrinology"],
    experience: 12,
    verification_status: "verified",
    education: [
      {
        degree: "Doctor of Medicine",
        school: "National and Kapodistrian University of Athens",
      },
    ],
    bio: "Compassionate OB/GYN specializing in reproductive endocrinology and infertility. Dedicated to helping couples achieve their dreams of parenthood.",
    awards: [
      "Young Investigator Award - European Society of Human Reproduction and Embryology",
    ],
    rate: {
      amount: 170,
      lengthOfSession: 50,
    },
  },
  {
    notifications: {
      email: false,
      status: true,
      records: true,
      messages: false,
      appointments: true,
    },
    languages: ["English Language", "French", "Swahili"],
    email: "sophia.chen@example.com",
    isActive: true,
    firstName: "Sophia",
    lastName: "Chen",
    MDCRegistration: "753951456789",
    dob: "1988-11-23",
    gender: "female",
    contact: "0334567890",
    address: "45 Maple Avenue",
    city: "Toronto",
    qualifications: ["MD", "PhD in Neuroscience"],
    specializations: ["Neurology", "Pediatrics"],
    experience: 12,
    verification_status: "verified",
    education: [
      {
        degree: "Doctor of Medicine",
        school: "University of Toronto",
      },
      {
        degree: "PhD in Neuroscience",
        school: "Harvard University",
      },
    ],
    bio: "Passionate neurologist with a focus on pediatric neurodevelopmental disorders. Combining clinical expertise with cutting-edge research to improve patient outcomes. Advocate for accessible healthcare and mentorship in the medical field.",
    awards: [
      "Young Investigator Award - Neurology Society",
      "Excellence in Patient Care - Toronto General Hospital",
    ],
    rate: {
      amount: 200,
      lengthOfSession: 60,
    },
  },
];
